########################################################
## ansible-playbook -s local.yml
########################################################
- hosts: localhost

  become: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes cache_valid_time=3600
      changed_when: False
      ignore_errors: yes

  vars:
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"

    myDict:
     nas: "{{nas_user}}@{{nas_ip}}:{{nas_path_backup}}"
     hd: "{{ hd_path_backup }}"
    rsync_backup_path: '{{myDict[source_type | default("this key does not exist in the dict")] | default("") }}'

  tasks:
    - include: tasks/basic_settings.yml
    - include: tasks/packages.yml
    - include: tasks/git-repo.yml
    - include: tasks/cron.yml
    - include: tasks/post_packages_installation.yml
