########################################################
## ansible-playbook -s local.yml
########################################################
- hosts: localhost
#- hosts: all
  become: true
#  become_ask_pass: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes cache_valid_time=3600
      changed_when: False

  tasks:
    - include: packages.yml
    - include: cron.yml
