#------------------------------------------
# Get configurations from backup

- name: Get Remmina configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.remmina /home/{{main_user}}/
  ignore_errors: true

- name: Get Filezilla configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.filezilla /home/{{main_user}}/
  ignore_errors: true

- name: Get Google Chrome configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete --exclude-from=tasks/rsync_exclude_chrome.txt {{rsync_backup_path}}/.config/google-chrome /home/{{main_user}}/.config/
  ignore_errors: true

# configurazione SAPGUI (se prevista)
- name: Get SAPGUI configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.SAPGUI /home/{{main_user}}/
  ignore_errors: true
  when: cloud_sapapp != "no"

- name: Thunderbird configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.thunderbird /home/{{main_user}}/
  ignore_errors: true


#-------------------------------------------
# VPN Configurations

# BarracudaVPN
- name: BarracudaVPN
  shell: rsync -avz --ignore-errors /media/{{main_user}}/LupinCrypt/Backup/{{hostname}}/etc/barracudavpn/ /etc/barracudavpn/
  ignore_errors: true

# Network Manager
- name: Network Manager                        
  shell: rsync -avz --ignore-errors /media/{{main_user}}/LupinCrypt/Backup/{{hostname}}/etc/NetworkManager/ /etc/NetworkManager/
  ignore_errors: true

#-------------------------------------------
# Other settings

- name: Add Telegram to auto-start applications
  copy:
    src: /usr/share/applications/telegramdesktop.desktop
    dest: /home/{{main_user}}/.config/autostart/telegramdesktop.desktop
    owner: "{{main_user}}"
    group: "{{main_user}}"
    mode: 0664

- name: change samba config to discover samba hosts netbios
  lineinfile:
    path: /etc/samba/smb.conf
#    regexp: '^Listen '
    insertafter: 'workgroup = WORKGROUP'
    line: '   client max protocol = NT1'

# .desktop files sync
- name: sync application .desktop
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors {{rsync_backup_path}}/.local/share/applications/ /home/{{main_user}}/.local/share/applications/
  ignore_errors: true

# local icons sync
- name: sync local icons
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors {{rsync_backup_path}}/.local/share/icons/ /home/{{main_user}}/.local/share/icons/
  ignore_errors: true

# sync document templates
- name: sync document templates
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors {{rsync_backup_path}}/Templates/ /home/{{main_user}}/Templates/
  ignore_errors: true

# sync Pictures
- name: sync Pictures
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors {{rsync_backup_path}}/Pictures/ /home/{{main_user}}/Pictures/
  ignore_errors: true

# sync shell scripts
- name: sync shell scripts
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors {{rsync_backup_path}}/*.sh /home/{{main_user}}/
  ignore_errors: true




