#------------------------------------------
# Get configurations from backup

- name: Get Remmina configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.remmina /home/{{main_user}}/
  ignore_errors: true

- name: Get Filezilla configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.filezilla /home/{{main_user}}/
  ignore_errors: true

- name: Get Google Chrome configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete --exclude-from=tasks/rsync_exclude_chrome.txt {{rsync_backup_path}}/.config/google-chrome /home/{{main_user}}/.config/
  ignore_errors: true

- name: Get SAPGUI configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.SAPGUI /home/{{main_user}}/
  ignore_errors: true

- name: Thunderbird configuration from backup
  become_user: "{{ main_user }}"
  shell: rsync -avz --ignore-errors --delete-excluded --delete {{rsync_backup_path}}/.thunderbird /home/{{main_user}}/
  ignore_errors: true


#-------------------------------------------
# Other settings

- name: Add Telegram to auto-start applications
  copy:
    src: /usr/share/applications/telegramdesktop.desktop
    dest: /home/{{main_user}}/.config/autostart/telegramdesktop.desktop
    owner: "{{main_user}}"
    group: "{{main_user}}"
    mode: 0664
